name: Deploy to Firebase Hosting PAVAN-SUPPORT

on:
  push:
    branches:
      - main
      - dev
      - uat

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "18"

      - name: Install Angular CLI
        run: npm install --save-dev @angular/cli@latest

      - name: Install dependencies
        run: npm install --force

      - name: Build the project
        run: npm run build

      - name: Set up Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy to Firebase Hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          if [ "${{ github.ref }}" == "refs/heads/main" ]; then
            firebase deploy --only hosting:pavan-support-web
          elif [ "${{ github.ref }}" == "refs/heads/dev" ]; then
            firebase deploy --only hosting:pavan-support-dweb
          elif [ "${{ github.ref }}" == "refs/heads/uat" ]; then
            firebase deploy --only hosting:pavan-support-uweb
          fi
